Add `calculate_centroid`, `define_rotation_matrix`
cmlibs-python/cmlibs.maths pull request #5
Opened 2024-01-31 04:20 UTC by tsalemink

Adds two functions required by the new `Orientation` and `Normal` handlers.

2024-01-31 21:41 UTC, hsorby commented on src/cmlibs/maths/algorithms.py
> +import numpy as np
A big part of this package is that it doesn't use numpy.

2024-01-31 21:56 UTC, hsorby requested changes

2024-01-31 21:56 UTC, hsorby commented on src/cmlibs/maths/algorithms.py
> +calculate_plane_normal = calculatePlaneNormal
This should be the other way around, rename the functions to the proper form and place the alternative here.

2024-01-31 21:56 UTC, hsorby commented on src/cmlibs/maths/algorithms.py
> +def calculate_rotation_matrix(vector_1, vector_2):
This function name can be better.  We want to indicate what it is creating the rotation matrix from.

2024-01-31 21:57 UTC, hsorby commented
> Adds two functions required by the new `Orientation` and `Normal` handlers.

Without a link this doesn't mean a whole lot.

2024-01-31 22:10 UTC, hsorby commented on src/cmlibs/maths/algorithms.py
> +    theta = math.acos(normal_dot_product / (normal1_length * normal2_length))
We already have this as a function `angle`.

2024-02-01 01:18 UTC, tsalemink commented on src/cmlibs/maths/algorithms.py
> +import numpy as np
I have removed the `numpy` dependency and updated the `calculate_centroid` function accordingly.

2024-02-01 01:18 UTC, tsalemink commented on src/cmlibs/maths/algorithms.py
> +calculate_plane_normal = calculatePlaneNormal
Done.

2024-02-01 01:25 UTC, tsalemink commented on src/cmlibs/maths/algorithms.py
> +    theta = math.acos(normal_dot_product / (normal1_length * normal2_length))
I hadn't noticed the existing `angle` function. My mistake. After simplifying `calculate_rotation_matrix` to use `angle`, I thought I'd be best to remove `calculate_rotation_matrix` entirely, since its implementation is simple enough to be called directly.

2024-02-01 01:30 UTC, tsalemink commented
> > Adds two functions required by the new `Orientation` and `Normal` handlers.
> 
> Without a link this doesn't mean a whole lot.

The link to the draft PR including the new `Orientation` and `Normal` handlers can be found [here](https://github.com/cmlibs-python/cmlibs.widgets/pull/67). The PR is a draft because it depends on another pending PR made to the same repository.

2024-02-02 00:07 UTC, hsorby requested changes
Looking really good, I think just a tiny bit of documentation will help others with this.

2024-02-02 00:07 UTC, hsorby commented on src/cmlibs/maths/algorithms.py
> +def calculate_centroid(data_points):
Can you describe the shape of the `data_points`input please.

2024-02-02 01:10 UTC, tsalemink commented on src/cmlibs/maths/algorithms.py
> +def calculate_centroid(data_points):
Yeah, good idea. I've just added some documentation for that function.

2024-02-02 01:13 UTC, hsorby commented on src/cmlibs/maths/algorithms.py
> +def calculate_centroid(data_points):
Is that a list of lists, `m`lists of size `n`?

2024-02-02 01:20 UTC, tsalemink commented on src/cmlibs/maths/algorithms.py
> +def calculate_centroid(data_points):
A list of lists, `n` lists of size `m`. I've updated the docstring.

2024-02-02 02:12 UTC, hsorby approved these changes

2024-02-02 02:12 UTC, merged