Scaffoldmaker vector
cmlibs-python/cmlibs.maths pull request #8
Opened 2024-04-18 04:04 UTC by Kayvv

Move scaffoldmaker vector functions to vectorops.py

2024-04-26 01:21 UTC, rchristie requested changes
Need to increment version to 0.6.0 and make that a dependency in scaffoldmaker.

2024-05-30 20:49 UTC, hsorby commented on src/cmlibs/maths/vectorops.py
> +def angle_between_vectors(u, v):
This needs to be called `angle` not `angle_between_vectors`.

2024-06-13 00:45 UTC, Kayvv commented on src/cmlibs/maths/vectorops.py
> +def angle_between_vectors(u, v):
Hi,
Using "angle" as the function name seems a bit ambiguous to me, especially since we have variables named "angle" in some parts of our code. I can change the function name to "angle" if you prefer. Should we also change the way we import the function to avoid confusion? Instead of using "from cmlibs.maths.vectorops import angle, ...", we could import the entire module with "import cmlibs.maths.vectorops" and call the function as "vectorops.angle()".
Let me know your thoughts.

2024-06-13 00:48 UTC, hsorby commented on src/cmlibs/maths/vectorops.py
> +def angle_between_vectors(u, v):
No just call it `angle`, and no don't use `vectorops.angle()`.

2024-07-23 06:36 UTC, hsorby commented
Superseded by #9.

2024-07-23 06:36 UTC, closed without merging